### ISSUE TITLE
Configuración con IPTV

### ISSUE THREAD

**Issue by ccorderod** [ger-ator/unifi-usg-movistar#1]
Hola @ger-ator 

No tendrás por ahí una configuración de USG-Pro-4 con las 3 vlanes de internet, iptv y voip?

Gracias.

**Comment by ger-ator** [comment]
En realidad mi proveedor es O2 así que no dispongo de servicio IPTV. Hay configuraciones para edgerouter disponibles fáciles de encontrar que te pueden servir de base para lo que quieres.

**Comment by ccorderod** [comment]
Busco. Muchas gracias.
